/**
 * Controls how `snapshotBones` extracts bones from the DOM.
 * Pass as `snapshotConfig` on `<BoneyardSkeleton>` or as the third arg to `snapshotBones()`.
 *
 * @example
 * <BoneyardSkeleton :loading="isLoading" :snapshot-config="{ leafTags: ['p', 'h1', 'h2', 'li'] }">
 *   <MyComponent />
 * </BoneyardSkeleton>
 */
export interface SnapshotConfig {
  /**
   * HTML tags always captured as a single atomic bone, regardless of children.
   * Use this for block-level text elements in your design system.
   * Default: ['p','h1','h2','h3','h4','h5','h6','li','tr']
   */
  leafTags?: string[];

  /**
   * When true, containers with a visible border AND border-radius are captured
   * as container bones — even with a white or transparent background.
   * Default: true
   */
  captureRoundedBorders?: boolean;

  /**
   * HTML tags to skip entirely — no bone emitted, children not walked.
   *
   * @example ['nav', 'footer', 'aside']
   */
  excludeTags?: string[];

  /**
   * CSS selectors to skip entirely. Any element matching a selector is
   * excluded along with all its descendants.
   *
   * @example
   * excludeSelectors: [
   *   '.icon',
   *   '[data-no-skeleton]',
   *   '#sidebar',
   * ]
   */
  excludeSelectors?: string[];
}

/** A single skeleton bone — a rounded rect placeholder */
export interface Bone {
  x: number;
  y: number;
  w: number;
  h: number;
  r: number | string;
  /** True if this bone is a background container — rendered lighter so children stand out */
  c?: boolean;
}

/** Skeleton layout result for a component at a specific width */
export interface SkeletonResult {
  name: string;
  viewportWidth: number;
  width: number;
  height: number;
  bones: Bone[];
}

/**
 * Describes a component's visual structure for skeleton generation.
 * Auto-extracted from the DOM via `fromElement()`, or hand-authored for
 * SSR/build-time paths where no DOM is available.
 */
export interface SkeletonDescriptor {
  display?: "block" | "flex";
  flexDirection?: "row" | "column";
  alignItems?: string;
  justifyContent?: string;
  width?: number;
  height?: number;
  aspectRatio?: number;
  padding?: number | { top?: number; right?: number; bottom?: number; left?: number };
  margin?: number | { top?: number; right?: number; bottom?: number; left?: number };
  gap?: number;
  rowGap?: number;
  columnGap?: number;
  borderRadius?: number | string;
  font?: string;
  lineHeight?: number;
  text?: string;
  maxWidth?: number;
  leaf?: boolean;
  children?: SkeletonDescriptor[];
}

/**
 * A responsive skeleton descriptor — maps min-width breakpoints to
 * structural variants.
 */
export type ResponsiveDescriptor = Record<number, SkeletonDescriptor>;

/**
 * Responsive bones — a set of SkeletonResults captured at different viewport widths.
 * Generated by `boneyard-vue build`, passed as `initialBones` to `<BoneyardSkeleton>`.
 */
export interface ResponsiveBones {
  breakpoints: Record<number, SkeletonResult>;
}
